services:
  - type: web
    name: vanich-backend
    env: docker
    plan: free
    dockerfilePath: ./backend/Dockerfile
    buildCommand: ""
    envVars:
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "vanich.onrender.com"

  - type: web
    name: vanich-frontend
    env: docker
    plan: free
    dockerfilePath: ./frontend/Dockerfile
    buildCommand: ""
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: https://vanich.onrender.com